get:
  tags:
    - Products
  summary: Get an existing product
  description: Return a single product by ID
  parameters:
    - name: productId
      in: path
      description: ID of product to return
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Successfully get product
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'          
    '404':
      description: Product not found
    '500':
      description: Internal server error
put: 
  tags:
    - Products
  summary: Update an existing product
  description: Update an existing product
  parameters:
    - name: productId
      in: path
      description: ID of product to update
      required: true
      schema:
        type: string
  requestBody:
    description: The content to update
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Product.yaml'
  responses:
    '200':
      description: Successfully update product
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'
    '400':
      description: Bad request
    '401':
      description: Unauthorized
    '404':
      description: Not found
    '500':
      description: Internal server error
  security:
    - api_key_authentication: []
delete:
  tags:
    - Products
  summary: Delete an existing product
  description: Delete an existing product by ID
  parameters:
    - name: productId
      in: path
      description: ID of product to delete
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Successfully delete product  
    '401':
      description: Unauthorized
    '404':
      description: Not found
    '500':
      description: Internal server error
  security:
    - api_key_authentication: []